# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds: []
#   - env:
#       - CGO_ENABLED=0
#     goos:
#       - linux
#       - windows
#       - darwin
# archives:
#   - replacements:
#       darwin: Darwin
#       linux: Linux
#       windows: Windows
#       386: i386
#       amd64: x86_64
#     format_overrides:
#       - goos: windows
#         format: zip
# checksum:
#   name_template: "checksums.txt"
dockers:
  - image_templates:
      - "ghcr.io/ryodocx/envoyproxy-dashboard:{{ .Tag }}"
      - "ghcr.io/ryodocx/envoyproxy-dashboard:v{{ .Major }}"
      - "ghcr.io/ryodocx/envoyproxy-dashboard:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/ryodocx/envoyproxy-dashboard:latest"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: false
  prerelease: auto
