// Code generated by entc, DO NOT EDIT.

package db

import (
	"github.com/ryodocx/envoyproxy-dashboard/backend/db/route"
	"github.com/ryodocx/envoyproxy-dashboard/backend/db/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescDomain is the schema descriptor for domain field.
	routeDescDomain := routeFields[0].Descriptor()
	// route.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	route.DomainValidator = routeDescDomain.Validators[0].(func(string) error)
}
